apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dataHandler-service-deployment
  namespace: development
  labels:
    app: dataHandler-service-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: dataHandler-service
    spec:
      containers:
      - name: dataHandler-service
        image: index.docker.io/v1/:proj/datahandler
        ports:
        - containerPort: 8083
